name: Deploy Kotlin Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21

    - name: Add secrets file
      run: |
        mkdir -p src/main/resources
        echo -e "spring.datasource.url=${{ secrets.DATABASE_URL }}\nspring.datasource.username=${{ secrets.DATABASE_USER }}\nspring.datasource.password=${{ secrets.PASSWORD }}\nspring.security.user.name=${{ secrets.DATABASE_USER }}\nspring.security.user.password=${{ secrets.PASSWORD }}" > src/main/resources/application.properties

    - name: Build with Gradle
      run: ./gradlew build

    - name: Copy Files to Server
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ubuntu
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        local: "./build/libs/party-building-0.0.1-SNAPSHOT.jar"
        remote: "/home/ubuntu/computer-design/party-building-0.0.1-SNAPSHOT.jar"

    - name: Restart Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          pgrep java | xargs kill -9
          nohup java -jar /home/ubuntu/computer-design/party-building-0.0.1-SNAPSHOT.jar &
